name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test All Components
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Generate gradlew if missing
      - name: Generate gradlew if missing
        run: |
          if [ ! -f ./FabricMod/gradlew ]; then
            echo "gradlew file is missing in FabricMod. Generating..."
            cd FabricMod
            gradle wrapper
            chmod +x ./gradlew
            cd ..
          fi
          if [ ! -f ./PaperPlugin/gradlew ]; then
            echo "gradlew file is missing in PaperPlugin. Generating..."
            cd PaperPlugin
            gradle wrapper
            chmod +x ./gradlew
            cd ..
          fi

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build FabricMod (Java)
      - name: Build FabricMod
        working-directory: FabricMod
        run: ./gradlew build --debug

      # Build PaperPlugin (Java)
      - name: Build PaperPlugin
        working-directory: PaperPlugin
        run: ./gradlew build --debug --stacktrace

      # Set up C++ environment
      - name: Install C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      # Build SR3Mod (C++)
      - name: Build SR3Mod
        working-directory: SR3Mod
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install Python dependencies
      - name: Install Python dependencies
        working-directory: BridgeServer
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint Python code
      - name: Lint Python code
        working-directory: BridgeServer
        run: |
          pip install flake8
          flake8 .
